---
title: 'ESM 244: Time Series Continued'
author: "Kiera Matiska"
date: "3/7/2022"
output: html_document
---

```{r setup, include=TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# attach packages
library(tidyverse)
library(here)
library(broom)

# Time series packages
library(tsibble)
library(feasts)
library(fable)
```

# Part 1: Time series wrangling and forecasting

### Read in data and convert to a tsibble

```{r}
energy <- read_csv(here("data", "energy.csv"))

energy_ts <- energy %>% 
  mutate(date = tsibble::yearmonth(month)) %>% 
  as_tsibble(key = NULL, index = date)
```

## Exploratory time series visualization {.tabset .tabset-fade}

### Raw data graph:

```{r}
ggplot(data = energy_ts,
       aes(x = date, y = res_total)) +
  geom_line() +
  labs(y = "Residential Energy Consumption \n (Trillion BTU)")
```

### Seasonplot:

```{r}
energy_ts %>% 
  gg_season(y = res_total) +
  theme_minimal() +
  scale_color_viridis_c() +
  labs(x = "Month",
       y = "Residential Energy Consumption \n (Trillion BTU)")
```

### Subseries plot:

```{r}
energy_ts %>% 
  gg_subseries(res_total)
```

### Decomposition (here by STL)

```{r}
# Find STL decomposition
dcmp <- energy_ts %>% 
  model(STL(res_total ~ season()))

# View the components
# components(dcmp)

# Visualize the decomposed components
components(dcmp) %>% 
  autoplot() +
  theme_minimal()
```

### Autocorrelation function (ACF)

```{r}
energy_ts %>% 
  ACF(res_total) %>% 
  autoplot()
```

## Forcasting by Holt-Winters Exponential Smoothing

```{r}
# Create the model:
energy_fit <- energy_ts %>% 
  model(
    ets = ETS(res_total ~ season("M"))
  )

# Forecast using the model 10 years into the future:
energy_forecast <- energy_fit %>% 
  forecast(h = "10 years")

# Plot just the forecasted values (with 80 & 95% CIs):
energy_forecast %>% 
  autoplot()

# Or plot it added to the original data:
energy_forecast %>% 
  autoplot(energy_ts)
```

### Assessing residuals

```{r}
# Append the predicted values (and residuals) to original energy data
energy_predicted <- broom::augment(energy_fit)

# Us View(energy_predicted) to see the resulting data frame
# View(energy_predicted)
```

```{r}
ggplot(data = energy_predicted) +
  geom_line(aes(x = date,
                y = res_total)) +
  geom_line(aes(x = date,
                y = .fitted),
            color = "red",
            alpha = 0.7)
```

```{r}
ggplot(data = energy_predicted,
       aes(x = .resid)) +
  geom_histogram()
```

## Other forecasting methods

```{r}
# Fit 3 different forecasting models (ETS, ARIMA, SNAIVE):
energy_fit_multi <- energy_ts %>% 
  model(
    ets = ETS(res_total ~ season("M")),
    arima = ARIMA(res_total),
    snaive = SNAIVE(res_total)
  )

# Forecast 3 years into the future (from data end date)
multi_forecast <- energy_fit_multi %>% 
  forecast(h = "3 years")

# Plot the 3 forecasts
multi_forecast %>% 
  autoplot(energy_ts)

# Or just view the forecasts (note the similarity across models):
multi_forecast %>% 
  autoplot()
```





