---
title: 'ESM 244 Lab 9: Strings in stringr & other stuff'
author: "Kiera Matiska"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# attach packages
library(tidyverse)
```

# Useful functions in `stringr`

### Detect a pattern

```{r}
# Make a little vector
vec <- c("A Unicorn Fish", "add cornmeal", "French FRIES", "acorn squash")

# Then detect a string pattern:
str_detect(vec, pattern = "corn")
str_detect(vec, pattern = "fish")
str_extract(vec, pattern = "[a-z]")
str_extract(vec, pattern = "[a-z]+")
str_extract_all(vec, pattern = "[a-zA-Z]+")
```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk"))
```

### Replace a pattern

```{r}
str_replace(vec, pattern = "corn", replacement = "COOL")

str_replace_all(vec, pattern = "a", replacement = "ZZZ")
```

```{r}
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))
```

### Remove White Space

```{r}
str_trim(vec) # Notice there are still excess spaces in the middle

str_squish(vec) # Notice that now trailing, leading and excess interior whitespaces are removed
```

### Change string case

```{r}
str_to_lower(vec)

str_to_upper(vec)

str_to_title(vec)
```

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "Llama")) %>% 
  mutate(name = str_to_lower(name))
```








